version: '3'

services:
  bot:
    depends_on:
      - postgres
      - redis
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    pull_policy: build
    networks:
      - network
    environment:
      - TOKEN=${TOKEN}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: npm start

  redis:
    image: redis:7.0.11
    # TODO: configure redis properly, either by using arguments or using a separate volume for configs.
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - network
    ports:
      - '6379'
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:13.11
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    networks:
      - network
    ports:
      - '5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data

networks:
  network:
    driver: bridge

volumes:
  postgresdata:
  redisdata:
